
```{r setup}
# Required packages
library("googledrive") # https://googledrive.tidyverse.org/
library("googlesheets4") # not sure if actually used tbh; read Google sheets
library("readxl") # read excel files; https://readxl.tidyverse.org/
library("stringr") # string manipulation
library("dplyr") # data manipulation
library("lubridate") # working with dates/times

# Make sure to authenticate Google account that's shared to the Kitchen Records folder
googledrive::drive_auth()
gs4_auth(token = drive_token())
```


```{r Roster}
# Download KC roster locally
# Was not able to read in xlsx file without downloading it :/
# Only need to run the code below only once or else will get an error
# Comment this out when running whole code; only need to comment it back if/when
# 'Roster' spreadsheet is updated

# drive_download(
#   as_id("https://docs.google.com/spreadsheets/d/1EIrRxF9gXLocFEEx5_ldjCIcuvDoXBfw/edit#gid=57217781",
#         path = "KC Planning.xlsx",
#         overwrite = TRUE,
#         type = "xlsx")
# )

# Read in roster of all KC's
KC_roster <- read_xlsx("KC Planning.xlsx", sheet = "Roster")

# Get current KCC
KCC <- KC_roster[grep("1", KC_roster$Role), 1:3]
# Get current AKCC(s)
AKCC <- KC_roster[grep("2", KC_roster$Role), 1:3]
# Get all other KCs
KCs <- KC_roster[grep("3", KC_roster$Role), 1:3]

# All current / permanent KCs
KC_current <- rbind(KCC, AKCC, KCs)
KC_current
# Overall roster of KCs both former and past plus deep cleaning
roster <- KC_roster[, 1:3]

# All names of current KCs
# Might be a problem with KCs who go by another name
# Will pull all KCs' first names, it would help if KCs who go by another name
# were the only ones with parentheses in their names
KC_names <- c()

for (i in 1:nrow(KC_current)) {
  
  # Account for KCs with other names
  if (str_detect(KC_current[i, 2], "\\(") == TRUE) {
    # Split name into separate characters
    name <- str_split(KC_current[i, 2], " ")
    # Extract character with parenthesis
    name <- name[[1]][str_detect(name[[1]], "\\(") == TRUE]
    # Remove parenthesis by splitting character, and extract name
    first_name <- str_split(name, "[\\W]")[[1]][2]

  } else {
    # Split name into separate characters
    name <- str_split(KC_current[i, 2], " ")
    # Extract only first name
    first_name <- name[[1]][1]
  }
  KC_names <- c(KC_names, first_name)
}

# Names of KCs according to the schedule
KC_names
```


```{r Filter}
records <- drive_ls(path = "Kitchen Records TEST")
records <- records[grepl("Records", records$name),]
records_CDF <- records[grepl("Records_Credit-Debit-Fine.csv", records$name),] # CDF = Credit_Debit_Fine
records_SI <- records[grepl("Records.csv", records$name),] # Sheets with times
```


```{r Clean sheets}

records <- drive_ls(path = "Kitchen Records TEST")

for (i in 1:nrow(records)){
  origname <- records$name[i]
  if (grepl("Copy of", origname)){
    fixname <- gsub("Copy of ", "", origname)
    drive_rename(file = as_id(records$id[i]), name = fixname, overwrite = T)
  }
}
```


```{r Read 1 sheet}
sheet <- records_SI[11, ]

sheet1 <- sheet %>%
  drive_read_string() %>%
  read.csv(text = .)

##################################################################
################# Preparing Data to Analyse Time #################
##################################################################

# Pattern used for grouping and capturing day
pattern_date <- "(\\d{8})"
# Get the day from the 'Identifier' variable
sheet_date <- str_match(sheet1$identifier, pattern_date)[1, 1]
# Convert times from chars to time variables
# First adding date to all time chars
for(i in 1:length(sheet1$identifier)) {
  # Start/end shift times
  sheet1$startTime[i] <- paste(sheet_date, sheet1$startTime[i])
  sheet1$endTime[i] <- paste(sheet_date, sheet1$endTime[i])
  
  # It does not make sense to append date to no-shows
  if (sheet1$signed.[i] != "false") {
    # Time logged in/out of shift
    sheet1$signInTime[i] <- paste(sheet_date, sheet1$signInTime[i])
    sheet1$signOutTime[i] <- paste(sheet_date, sheet1$signOutTime[i])
    
    # It does not make sense to append date when no break was taken
    if (is.na(sheet1$Duration[i]) != TRUE) {
      # Start/end break times
      sheet1$breakInTime[i] <- paste(sheet_date, sheet1$breakInTime[i])
      sheet1$breakoutTime[i] <- paste(sheet_date, sheet1$breakoutTime[i])
    }
  }
}

# Finally convert all time cols to POSIXct's
# Note: Missing times will turn into NA's
sheet1$startTime <- as.POSIXct(sheet1$startTime, format = "%Y%m%d %H:%M")
sheet1$endTime <- as.POSIXct(sheet1$endTime, format = "%Y%m%d %H:%M")
sheet1$signInTime <- as.POSIXct(sheet1$signInTime, format = "%Y%m%d %H:%M")
sheet1$signOutTime <- as.POSIXct(sheet1$signOutTime, format = "%Y%m%d %H:%M")
sheet1$breakInTime <- as.POSIXct(sheet1$breakInTime, format = "%Y%m%d %H:%M")
sheet1$breakoutTime <- as.POSIXct(sheet1$breakoutTime, format = "%Y%m%d %H:%M")

# View sheet with appropriate time variables
# We can always extract only our calculations and append
# them to original sheet for aesthetic purposes
sheet1

# Total length of shift
# 4-hour shifts should be around 220mins (counting the break)
shift_length <- if_else(difftime(sheet1$endTime, sheet1$startTime,
                                 units = "mins") >= 240,
                        difftime(sheet1$endTime, sheet1$startTime,
                                 units = "mins") - 20,
                        difftime(sheet1$endTime, sheet1$startTime,
                                 units = "mins"))

# Set late threshold to 15 mins
# 15 x 60 = 900secs
late_mins <- sheet1$startTime + 900

# Gather information about workers
# Were they late? How late? Did they take a long break? Did they leave early?
sheet2 <- sheet1 %>% 
  # Deselect columns we don't need
  select(-identifier, -room, -shiftType, -assigned.by,
         -signed., -(checked.:notes)) %>% 
  mutate(
    # Determine who was more than 15mins late
    # Want to have a check for workers who began at 5pm
    late = if_else((str_detect(startTime, "17") != TRUE) &
                      late_mins < signInTime, "Late",
                   if_else((str_detect(startTime, "17") == TRUE) &
                      late_mins + 1200 < signInTime, "Late", "On Time")),
    # Calculate how many mins worker was late
    # Have a late check for workers who began at 5pm
    total_mins_late = if_else((late == "Late") & (is.na(late) != TRUE) &
                                str_detect(startTime, "17") != TRUE,
                              difftime(signInTime, late_mins, units = "mins"),
                         if_else((late == "Late") &
                                   str_detect(startTime, "17") == TRUE,
                                 difftime(signInTime, late_mins,
                                          units = "mins") - 20, 0)),
    # Calculate how long shift was worked
    # This is calculated assuming they took a 20min break
    # However, it would be better to replace the 20 with 'Duration',
    # and fix it to a 20min break if greater than 40mins?
    # Having a break longer than 70mins is unrealistic, and so is having a
    # shift longer than 4 hours?
    # If worker forgot to end break, then perhaps it was caught when they
    # signed out, or did they also forget to sign out?
    worked = if_else((is.na(signInTime) == FALSE) &
                             (is.na(breakInTime) == FALSE),
                     # Subtract the 20min break
                     difftime(signOutTime, signInTime, units = "mins") - 20,
                     if_else(is.na(signInTime) == FALSE,
                             difftime(signOutTime, signInTime,
                                      units = "mins"), 0)),
    # Calculate how early worker left
    # Keep in mind that 5pm workers should have left at around a similar time
    left_early = if_else(is.na(signInTime) == FALSE & shift_length > worked,
                         shift_length - worked, 0)
    )

# View changes
sheet2
```


## Merge Month for Sign In

Test set is
- 052022
- 062022
- 072022

Make function that can parse dates from sheets

day format: MMDDYYYY
month format: MMYYYY

```{r Info table}
# Get dates from info
info_SI <- records_SI[,c(1,2)]
info_SI$date <- mdy(sub("_.*", "", info_SI$name))
info_SI$month <- month(info_SI$date)
info_SI$day <- wday(info_SI$date, label=T)
info_SI$year <- year(info_SI$date)
```


```{r Collate sheets per month}
collect_month <- function(month_idx, year = 2022, KC = F, upload = F) {
  
  #### ADD CHECK IF FILE ALREADY EXISTS HERE ####
  
  info_month <- info_SI[info_SI$month==month_idx & info_SI$year==year,]
  info_month <- info_month[order(info_month$date), ]
  out_title <- paste0(as.character(info_month$date[1],format="%m%Y"),"_Records")
  
  days <- days_in_month(info_month$date[1])
  if (nrow(info_month) != days) {  # Month is incomplete
    print("Month incomplete! Output will be partial month - ", nrow(info_month), " entries")
    out_title <- paste0(out_title, "_PARTIAL_", nrow(info_month))
  } else { #
    print(paste0(month(month_idx, label = T), " sheets all present!"))
  }
  
  month_sheet <- data.frame()
  
  for (day in 1:nrow(info_month)){ # Loop through all days in month
    day_cur <- info_month$date[day]
    print(paste0("** Collecting ", day_cur,"..."))
    day_id <- info_month$id[day]
    # Load sheet from id
    day_row <- records_SI[records_SI$id == day_id,]
    day_sheet <- day_row %>%
      drive_read_string() %>%
      read.csv(text = .)
    day_sheet$date <- day_cur
    month_sheet <- rbind(month_sheet, day_sheet)
  }
  # KC only
  month_sheet_KC <- month_sheet[month_sheet$role == "KC",]
  
  if (upload) {
    dir.create("tmp/")
    write.table(month_sheet, file = paste0("tmp/", out_title, ".csv"), sep = ",", quote = F, row.names = F)
    drive_upload(
      paste0("tmp/", out_title, ".csv"),
      path = paste0("Kitchen_Summary/", out_title, ".csv"),
      overwrite = T
    )
    write.table(month_sheet_KC, file = paste0("tmp/", out_title, "_KC.csv"), sep = ",", quote = F, row.names = F)
    drive_upload(
      paste0("tmp/", out_title, "_KC.csv"),
      path = paste0("Kitchen_Summary/", out_title, "_KC.csv"),
      overwrite = T
    )
    unlink("tmp/", recursive = T)
  }
  
  if (KC) {
    sheet_out <- month_sheet_KC
  } else {
    sheet_out <- month_sheet
  }
  sheet_out
}

month_idxs <- sort(unique(info_SI$month))

list_months <- list()
for (idx in month_idxs){
  list_months[[idx]] <- collect_month(idx, upload = T)
}

```


