
```{r setup}
# Required packages
library("googledrive") # https://googledrive.tidyverse.org/
library("googlesheets4") # not sure if actually used tbh
library("dplyr") # data manipulation
library("lubridate") # working with dates/times

# Make sure to authenticate Google account that's shared to the Kitchen Records folder
googledrive::drive_auth()
gs4_auth(token = drive_token())
```

```{r Filter}
records <- drive_ls(path = "Kitchen Records TEST")
records <- records[grepl("Records", records$name),]
records_CDF <- records[grepl("Records_Credit-Debit-Fine.csv", records$name),] # CDF = Credit_Debit_Fine
records_SI <- records[grepl("Records.csv", records$name),] # Sheets with times
```
```{r Clean sheets}
records <- drive_ls(path = "Kitchen Records TEST")

for (i in 1:nrow(records)){
  origname <- records$name[i]
  if (grepl("Copy of", origname)){
    fixname <- gsub("Copy of ", "", origname)
    drive_rename(file = as_id(records$id[i]), name = fixname, overwrite = T)
  }
}
```


```{r Read 1 sheet}
sheet <- records_SI[1,]

sheet1 <- sheet %>%
  drive_read_string() %>%
  read.csv(text = .)

sheet1 %>%
  select()
```


## Merge Month for Sign In

Test set is
- 052022
- 062022
- 072022

Make function that can parse dates from sheets

day format: MMDDYYYY
month format: MMYYYY

```{r Info table}
# Get dates from info
info_SI <- records_SI[,c(1,2)]
info_SI$date <- mdy(sub("_.*", "", info_SI$name))
info_SI$month <- month(info_SI$date)
info_SI$day <- wday(info_SI$date, label=T)
info_SI$year <- year(info_SI$date)
```


```{r Collate sheets per month}
collect_month <- function(month_idx, year = 2022, KC = F, upload = F) {
  
  #### ADD CHECK IF FILE ALREADY EXISTS HERE ####
  
  info_month <- info_SI[info_SI$month==month_idx & info_SI$year==year,]
  info_month <- info_month[order(info_month$date), ]
  out_title <- paste0(as.character(info_month$date[1],format="%m%Y"),"_Records")
  
  days <- days_in_month(info_month$date[1])
  if (nrow(info_month) != days) {  # Month is incomplete
    print("Month incomplete! Output will be partial month - ", nrow(info_month), " entries")
    out_title <- paste0(out_title, "_PARTIAL_", nrow(info_month))
  } else { #
    print(paste0(month(month_idx, label = T), " sheets all present!"))
  }
  
  month_sheet <- data.frame()
  
  for (day in 1:nrow(info_month)){ # Loop through all days in month
    day_cur <- info_month$date[day]
    print(paste0("** Collecting ", day_cur,"..."))
    day_id <- info_month$id[day]
    # Load sheet from id
    day_row <- records_SI[records_SI$id == day_id,]
    day_sheet <- day_row %>%
      drive_read_string() %>%
      read.csv(text = .)
    day_sheet$date <- day_cur
    month_sheet <- rbind(month_sheet, day_sheet)
  }
  # KC only
  month_sheet_KC <- month_sheet[month_sheet$role == "KC",]
  
  if (upload) {
    dir.create("tmp/")
    write.table(month_sheet, file = paste0("tmp/", out_title, ".csv"), sep = ",", quote = F, row.names = F)
    drive_upload(
      paste0("tmp/", out_title, ".csv"),
      path = paste0("Kitchen_Summary/", out_title, ".csv"),
      overwrite = T
    )
    write.table(month_sheet_KC, file = paste0("tmp/", out_title, "_KC.csv"), sep = ",", quote = F, row.names = F)
    drive_upload(
      paste0("tmp/", out_title, "_KC.csv"),
      path = paste0("Kitchen_Summary/", out_title, "_KC.csv"),
      overwrite = T
    )
    unlink("tmp/", recursive = T)
  }
  
  if (KC) {
    sheet_out <- month_sheet_KC
  } else {
    sheet_out <- month_sheet
  }
  sheet_out
}

month_idxs <- sort(unique(info_SI$month))

list_months <- list()
for (idx in month_idxs){
  list_months[[idx]] <- collect_month(idx, upload = T)
}

```

# Summary sheets
```{r Load summary sheets}
records_summary <- drive_ls(path = "Kitchen_Summary")
records_summary_KC <- records_summary[grepl("Records_KC", records_summary$name),]
records_summary_all <- records_summary[grepl("Records\\.", records_summary$name),]

all_records <- data.frame()
# sheet <- records_SI[1,]

for (i in 1:nrow(records_summary_all)){
  entry <- records_summary_all[i,]
  sheet <- entry %>%
    drive_read_string() %>%
    read.csv(text = .)
  all_records <- rbind(all_sheets, sheet)
}

head(all_records)
```

```{r Get KC Roster}
KC_path <- drive_get(path = "KC Planning.xlsx")
dir.create("tmp/")
drive_download(KC_path, path = "tmp/KC_Roster.xlsx", overwrite = T)
KC_roster <- readxl::read_excel("tmp/KC_Roster.xlsx", sheet = "Roster")
unlink("tmp/", recursive = T)
```






